"""
home.py — Home Page
Research-grade landing page with deepfake education, ethics disclaimer, and CTA.
"""

import streamlit as st
from frontend.styles import inject_css, section_header, gradient_divider


def render():
    inject_css()

    # ── Hero Section ──────────────────────────────────────────────
    st.markdown("""
    <div class="hero-container">
        <div class="hero-badge">🔬 IEEE-Research Grade System</div>
        <div class="hero-title">Deepfake Detection<br>& Explainability</div>
        <div class="hero-subtitle">
            An advanced AI system using EfficientNet-B0 and Grad-CAM to detect synthetic faces
            with transparency, confidence scoring, and human-readable explanations.
        </div>
    </div>
    """, unsafe_allow_html=True)

    # ── CTA Button ───────────────────────────────────────────────
    col1, col2, col3 = st.columns([2, 1, 2])
    with col2:
        if st.button("🔍  Upload & Detect", use_container_width=True):
            st.session_state["page"] = "🔍 Detect"
            st.rerun()  # Safe: session_state["page"] is always initialized in app.py before render()

    gradient_divider()

    # ── What is a Deepfake? ──────────────────────────────────────
    section_header("🧠", "What is a Deepfake?", "EDUCATION")

    col_a, col_b = st.columns(2, gap="large")
    with col_a:
        st.markdown("""
        <div class="glass-card">
            <h3>📖 Definition</h3>
            <p style="color:#C4C4D4; line-height:1.8;">
                A <strong style="color:#A78BFA">deepfake</strong> is a synthetic media — image, video, or audio —
                generated by deep neural networks (typically GANs or diffusion models) to make a person appear
                to say or do something they never did.
            </p>
            <p style="color:#C4C4D4; line-height:1.8; margin-top:0.75rem;">
                The term comes from combining <em>"deep learning"</em> and <em>"fake"</em>.
                Modern deepfakes use <strong>Generative Adversarial Networks (GANs)</strong> or
                <strong>Diffusion Models</strong> to synthesize photorealistic facial manipulations.
            </p>
        </div>
        """, unsafe_allow_html=True)

    with col_b:
        st.markdown("""
        <div class="glass-card">
            <h3>⚙️ How Are Deepfakes Made?</h3>
            <ul style="color:#C4C4D4; line-height:2; margin:0; padding-left:1.2rem;">
                <li><strong style="color:#A78BFA">Face Swap</strong> — replaces one person's face with another</li>
                <li><strong style="color:#A78BFA">Face Reenactment</strong> — transfers expressions/movements</li>
                <li><strong style="color:#06B6D4">GAN Synthesis</strong> — generates entirely new faces</li>
                <li><strong style="color:#06B6D4">Diffusion Models</strong> — state-of-the-art image generation</li>
                <li><strong style="color:#F59E0B">Audio Deepfakes</strong> — clones voice from short recordings</li>
            </ul>
        </div>
        """, unsafe_allow_html=True)

    gradient_divider()

    # ── Why Detection Matters ─────────────────────────────────────
    section_header("⚠️", "Why Detection Matters", "IMPACT")

    cols = st.columns(3, gap="medium")
    concerns = [
        ("🗳️", "Political Manipulation",
         "Deepfakes of political figures can spread disinformation, undermine elections, "
         "and erode trust in democratic institutions."),
        ("📰", "Media Integrity",
         "Synthetic media threats journalism and evidence credibility. Courts and "
         "newsrooms increasingly face fabricated video as 'proof'."),
        ("👤", "Personal Harm",
         "Non-consensual deepfakes are used for harassment, defamation, and identity theft — "
         "disproportionately targeting women and public figures."),
    ]
    for col, (icon, title, desc) in zip(cols, concerns):
        with col:
            st.markdown(f"""
            <div class="glass-card" style="height:100%;">
                <div style="font-size:2rem; margin-bottom:0.5rem;">{icon}</div>
                <h3>{title}</h3>
                <p style="color:#C4C4D4; line-height:1.75; font-size:0.9rem;">{desc}</p>
            </div>
            """, unsafe_allow_html=True)

    gradient_divider()

    # ── System Capabilities ───────────────────────────────────────
    section_header("🛡️", "System Capabilities", "FEATURES")
    cap_cols = st.columns(4, gap="medium")
    capabilities = [
        ("🎯", "High Accuracy", "Trained on FaceForensics++, Celeb-DF & DFDC"),
        ("🔥", "Grad-CAM XAI", "Visual explanations for every prediction"),
        ("📊", "Research Metrics", "Full ROC, confusion matrix, cross-dataset results"),
        ("🎬", "Video Analysis", "Frame-by-frame deepfake timeline"),
    ]
    for col, (icon, cap, desc) in zip(cap_cols, capabilities):
        with col:
            st.markdown(f"""
            <div class="glass-card" style="text-align:center;">
                <div style="font-size:2rem;">{icon}</div>
                <div style="font-weight:700; margin:0.5rem 0; color:#A78BFA;">{cap}</div>
                <div style="color:#8B8BA7; font-size:0.82rem;">{desc}</div>
            </div>
            """, unsafe_allow_html=True)

    gradient_divider()

    # ── Ethics Disclaimer ─────────────────────────────────────────
    section_header("⚖️", "Research Ethics & Disclaimer")
    st.markdown("""
    <div class="warning-box">
        <strong>⚠️ Important Disclaimer</strong><br><br>
        This system is a <strong>research and educational tool</strong>. Predictions should not be treated
        as conclusive legal evidence. AI detection systems can make errors — especially against
        high-quality synthetic media, extreme angles, or heavy compression.
        <br><br>
        This tool was built for <strong>academic research</strong>, media literacy education, and
        responsible AI development. It is not intended to be used for surveillance, profiling,
        or discrimination.
    </div>
    """, unsafe_allow_html=True)

    st.markdown("""
    <div class="info-box">
        <strong>📚 Training Data</strong> — This model was designed for training on publicly available
        research datasets: <em>FaceForensics++</em>, <em>Celeb-DF v2</em>, and <em>DFDC (Facebook AI)</em>.
        Cross-dataset validation demonstrates generalization beyond training distribution.
    </div>
    """, unsafe_allow_html=True)
